export const SHOW_ERROR = 'APP/SHOW_ERROR'
export const HIDE_ERROR = 'APP/HIDE_ERROR'

export const FETCH_USERS_SUCCESS = 'DATA/FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'DATA/FETCH_USERS_FAILURE'
export const FETCH_USERS_REQUEST = 'DATA/FETCH_USERS_REQUEST'

export const FETCH_POSTS_SUCCESS = 'DATA/FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'DATA/FETCH_POSTS_FAILURE'
export const FETCH_POSTS_REQUEST = 'DATA/FETCH_POSTS_REQUEST'

export const FETCH_COMMENTS_SUCCESS = 'DATA/FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILURE = 'DATA/FETCH_COMMENTS_FAILURE'
export const FETCH_COMMENTS_REQUEST = 'DATA/FETCH_COMMENTS_REQUEST'

export const ADD_POSTS_SUCCESS = 'DATA/ADD_POSTS_SUCCESS'
export const ADD_POSTS_FAILURE = 'DATA/ADD_POSTS_FAILURE'
export const ADD_POSTS_REQUEST = 'DATA/ADD_POSTS_REQUEST'

export const ADD_COMMENTS_SUCCESS = 'DATA/ADD_COMMENTS_SUCCESS'
export const ADD_COMMENTS_FAILURE = 'DATA/ADD_COMMENTS_FAILURE'
export const ADD_COMMENTS_REQUEST = 'DATA/ADD_COMMENTS_REQUEST'
